repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/rstcheck/rstcheck
    rev: "v6.2.0"
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        args: ["--config=.rstcheck.cfg"]
  - repo: https://github.com/twisted/towncrier
    rev: 23.11.0
    hooks:
      - id: towncrier-check

  # - repo: https://github.com/numpy/numpydoc
  #   rev: v1.6.0
  #   hooks:
  #     - id: numpydoc-validation
